In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("prestamos_automovil.csv")
df.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
0,O77MPJ,26,19153.0,6973,706,9.0,1,19.05,36.0,0.10,Grado Universitario,Jornada completa,Soltero,0.0,1.0,Automóvil,1.0,1,130.83
1,IYOL1S,29,39531.0,40000,826,0.0,1,9.74,24.0,0.19,Doctorado,Jornada completa,Casado,0.0,0.0,Automóvil,1.0,0,208.64
2,FRMZVN,29,40348.0,16448,740,9.0,1,14.73,24.0,0.10,Máster,Jornada completa,Soltero,0.0,1.0,Automóvil,0.0,1,101.94
3,YKHXVY,38,41732.0,42040,661,173.0,2,13.24,48.0,0.18,Grado Universitario,Tiempo parcial,Casado,1.0,0.0,Automóvil,1.0,1,800.00
4,NHDJTK,35,35085.0,16406,759,181.0,1,9.74,36.0,0.13,Escolar,Jornada completa,Casado,0.0,1.0,Automóvil,0.0,0,94.42

In [3]:
print("Filas:", len(df))

Filas: 76924

## Datos Necesarios

In [4]:
PAGOS_AÑO = 12   # cuotas mensuales

df["Num_Cuotas"] = df["Duracion"]
df["Tipo_Interes_Anual"] = df["Ratio_Interes"] / 100
df["Tipo_Interes_Mensual"] = df["Tipo_Interes_Anual"] / PAGOS_AÑO

P = df["Monto_Inicial"]
n = df["Num_Cuotas"]
i = df["Tipo_Interes_Mensual"]

df[["Monto_Inicial", "Num_Cuotas", "Tipo_Interes_Anual", "Tipo_Interes_Mensual"]].head()

   Monto_Inicial  Num_Cuotas  Tipo_Interes_Anual  Tipo_Interes_Mensual
0           6973        36.0              0.1905              0.015875
1          40000        24.0              0.0974              0.008117
2          16448        24.0              0.1473              0.012275
3          42040        48.0              0.1324              0.011033
4          16406        36.0              0.0974              0.008117